### ISSUE TITLE
Unable to compile Assimp so that I can debug problem with importing in LumixEngine.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine_3rdparty#1]
c:\development\lumixengine_3rdparty\3rdparty\assimp\code\version.cpp(67): fatal error C1083: Cannot open include file: 'revision.h': No such file or directory

Any information would be greatly appreciated.

**Comment by nem0** [comment]
I will try to fix this but in the meantime you can create revision.h in assimp's include directory looking like this:

```
#ifndef ASSIMP_REVISION_H_INC
#define ASSIMP_REVISION_H_INC

#define GitVersion 0x0
#define GitBranch "master"

#endif // ASSIMP_REVISION_H_INC
```

By the way you do not need to build assimp yourself to debug it, there is already a prebuilt library with debug information. Assimp has a lot of issues and I am considering to get rid of it and use fbx sdk, it supports far less formats but at least they 99% work.

**Comment by PeaceSells50** [comment]
Wow, so awesome! Thank you so much!
